oneup_flysystem:
    filesystems:
        asset_storage:
            adapter: asset_storage_adapter
            mount: assetStorage
        catalog_storage:
            adapter: catalog_storage_adapter
            mount: catalogStorage
        archivist:
            adapter: archivist_adapter
            mount: archivist
        jobs_storage:
            adapter: jobs_storage_adapter
            mount: jobsStorage
